/**
 * Catálogo de minijuegos.
 *
 * Esta es la única lista de la que sale el Centro de entrenamiento. Para
 * agregar un juego nuevo se mete una entrada aquí; no hay que tocar el
 * ruteo ni la pantalla del centro.
 *
 * Campos de cada juego:
 *   id           identificador estable (se usa para guardar el récord)
 *   nombre, icono, descripcion, comoSeJuega
 *   familia      "tecnito" | "greencito" | "general"  → decide la moneda
 *   categoria    subsección dentro del centro
 *   personaje    "sismo" | "green"  → tema visual y mascota
 *   motor        componente que lo juega
 *   xp           XP necesaria para desbloquearlo (0 = disponible desde el inicio)
 *   dificultades cuáles se ofrecen (por omisión, las tres)
 *   + los datos que necesite su motor (banco, escenas, rutas, cultivo...)
 */

import Quiz from "./motores/Quiz.jsx";
import Busca from "./motores/Busca.jsx";
import Clasifica from "./motores/Clasifica.jsx";
import Ruta from "./motores/Ruta.jsx";
import Cultiva from "./motores/Cultiva.jsx";
import Simulacion from "./motores/Simulacion.jsx";
import Construye from "./motores/Construye.jsx";
import Coloca from "./motores/Coloca.jsx";
import Codigo from "./motores/Codigo.jsx";
import Sopa from "./motores/Sopa.jsx";
import Puzzle from "./motores/Puzzle.jsx";
import Ruleta from "./motores/Ruleta.jsx";
import Atrapa from "./motores/Atrapa.jsx";
import { MemoramaCentro, SimulacroCentro, BasuraCentro } from "./motores/Clasicos.jsx";

export const FAMILIAS = {
  tecnito: { id: "tecnito", nombre: "Tecnito", icono: "🛡️", moneda: "escudos", monedaIcono: "🛡️" },
  greencito: { id: "greencito", nombre: "Greencito", icono: "🌱", moneda: "semillas", monedaIcono: "🌱" },
  general: { id: "general", nombre: "Desafíos", icono: "🧠", moneda: "puntos", monedaIcono: "⭐" },
};

export const JUEGOS = [
  /* ============================ 🛡️ TECNITO ============================ */
  {
    id: "ruta-evacuacion",
    nombre: "Ruta de evacuación",
    icono: "🏃",
    familia: "tecnito",
    categoria: "Evacuación",
    personaje: "sismo",
    motor: Ruta,
    rutas: "ruta-evacuacion",
    xp: 0,
    descripcion: "Sal del edificio por la ruta segura antes de que se acabe el tiempo.",
    comoSeJuega: "Muévete con las flechas, WASD o la cruceta. Esquiva las zonas de riesgo y recoge el extintor.",
  },
  {
    id: "agachate",
    nombre: "Agáchate, cúbrete y agárrate",
    icono: "🛡️",
    familia: "tecnito",
    categoria: "Sismos",
    personaje: "sismo",
    motor: Quiz,
    banco: "agachate",
    rondas: 8,
    segundos: 14,
    xp: 0,
    descripcion: "Está temblando en distintos lugares. Elige rápido la acción correcta.",
    comoSeJuega: "Poco tiempo por situación. Cada error explica qué había que hacer.",
  },
  {
    id: "casa-segura",
    nombre: "Casa segura",
    icono: "🏠",
    familia: "tecnito",
    categoria: "Sismos",
    personaje: "sismo",
    motor: Busca,
    escenas: "casa-segura",
    objetivos: 5,
    segundos: 60,
    verbo: "riesgos",
    xp: 0,
    descripcion: "Encuentra los riesgos de una casa antes de que tiemble.",
    comoSeJuega: "Toca lo que puede caerse, romperse o bloquear la salida. Tocar algo seguro cuesta una vida.",
  },
  {
    id: "mochila-emergencia",
    nombre: "Mochila de emergencia",
    icono: "🎒",
    familia: "tecnito",
    categoria: "Emergencias",
    personaje: "sismo",
    motor: Clasifica,
    clasificacion: "mochila-emergencia",
    rondas: 10,
    segundos: 8,
    xp: 0,
    descripcion: "Decide qué se va a la mochila y qué se queda en casa.",
    comoSeJuega: "Arrastra el objeto al contenedor o toca el contenedor directamente.",
  },
  {
    id: "simulacro",
    nombre: "Simulacro relámpago",
    icono: "🚨",
    familia: "tecnito",
    categoria: "Sismos",
    personaje: "sismo",
    motor: SimulacroCentro,
    xp: 0,
    dificultades: ["facil", "dificil"],
    descripcion: "Toca las tres acciones en orden mientras la pantalla tiembla.",
    comoSeJuega: "Agáchate, cúbrete y agárrate. Cuidado con los botones trampa.",
  },
  {
    id: "escuela-segura",
    nombre: "Escuela segura",
    icono: "🏫",
    familia: "tecnito",
    categoria: "Evacuación",
    personaje: "sismo",
    motor: Busca,
    escenas: "escuela-segura",
    objetivos: 5,
    segundos: 60,
    verbo: "fallas",
    xp: 40,
    descripcion: "Revisa el pasillo de tu escuela y encuentra las fallas de seguridad.",
    comoSeJuega: "Busca salidas bloqueadas, extintores vencidos y señales borradas.",
  },
  {
    id: "detective-riesgos",
    nombre: "Detective de riesgos",
    icono: "🔎",
    familia: "tecnito",
    categoria: "Emergencias",
    personaje: "sismo",
    motor: Busca,
    escenas: "detective-riesgos",
    objetivos: 5,
    segundos: 50,
    verbo: "riesgos",
    xp: 60,
    descripcion: "Cinco cosas en esta recámara pueden lastimarte si tiembla de noche.",
    comoSeJuega: "Encuéntralas todas antes de que se acabe el tiempo.",
  },
  {
    id: "incendio",
    nombre: "Incendio",
    icono: "🔥",
    familia: "tecnito",
    categoria: "Incendios",
    personaje: "sismo",
    motor: Quiz,
    banco: "incendio",
    rondas: 8,
    segundos: 18,
    xp: 60,
    descripcion: "Ocho situaciones de incendio. Decide qué haces en cada una.",
  },
  {
    id: "llamada-emergencia",
    nombre: "Llamada de emergencia",
    icono: "🚑",
    familia: "tecnito",
    categoria: "Emergencias",
    personaje: "sismo",
    motor: Quiz,
    banco: "llamada-emergencia",
    rondas: 6,
    segundos: 20,
    piel: "llamada",
    xp: 80,
    descripcion: "Estás llamando al 911. Da bien la información que te piden.",
    comoSeJuega: "Qué pasó, dónde, cuántas personas y qué riesgos hay.",
  },
  {
    id: "extintor",
    nombre: "Extintor correcto",
    icono: "🧯",
    familia: "tecnito",
    categoria: "Incendios",
    personaje: "sismo",
    motor: Quiz,
    banco: "extintor",
    rondas: 6,
    segundos: 20,
    xp: 100,
    descripcion: "Cada tipo de fuego necesita su extintor. Elige el correcto.",
  },
  {
    id: "fuga-gas",
    nombre: "Fuga de gas",
    icono: "☁️",
    familia: "tecnito",
    categoria: "Emergencias",
    personaje: "sismo",
    motor: Quiz,
    banco: "fuga-gas",
    rondas: 5,
    segundos: 18,
    xp: 120,
    descripcion: "Huele a gas. Una chispa basta: elige bien cada paso.",
  },
  {
    id: "volcan",
    nombre: "Volcán",
    icono: "🌋",
    familia: "tecnito",
    categoria: "Fenómenos naturales",
    personaje: "sismo",
    motor: Quiz,
    banco: "volcan",
    rondas: 4,
    segundos: 20,
    xp: 150,
    descripcion: "Semáforo volcánico, ceniza y evacuación.",
  },
  {
    id: "inundacion",
    nombre: "Inundación",
    icono: "🌊",
    familia: "tecnito",
    categoria: "Fenómenos naturales",
    personaje: "sismo",
    motor: Quiz,
    banco: "inundacion",
    rondas: 4,
    segundos: 20,
    xp: 150,
    descripcion: "El agua sube. Identifica las zonas seguras y decide.",
  },

  {
    id: "electricidad",
    nombre: "Electricidad",
    icono: "⚡",
    familia: "tecnito",
    categoria: "Emergencias",
    personaje: "sismo",
    motor: Busca,
    escenas: "electricidad",
    objetivos: 5,
    segundos: 50,
    verbo: "riesgos",
    xp: 120,
    descripcion: "Encuentra los riesgos eléctricos del taller antes de que alguien reciba un toque.",
  },
  {
    id: "construye-edificio",
    nombre: "Construye un edificio",
    icono: "🏗️",
    familia: "tecnito",
    categoria: "Sismos",
    personaje: "sismo",
    motor: Construye,
    construccion: "construye-edificio",
    xp: 180,
    descripcion: "Suelo, cimentación, columnas, trabes y muros. Al final, un sismo de 7.5 pone a prueba tu obra.",
    comoSeJuega: "En difícil no sabrás si acertaste hasta que tiemble, igual que en la vida real.",
  },
  {
    id: "mapa-riesgos",
    nombre: "Mapa de riesgos",
    icono: "🗺️",
    familia: "tecnito",
    categoria: "Fenómenos naturales",
    personaje: "sismo",
    motor: Busca,
    escenas: "mapa-riesgos",
    objetivos: 5,
    segundos: 55,
    verbo: "riesgos",
    xp: 160,
    descripcion: "Marca las zonas peligrosas de tu colonia sin tocar los refugios ni las salidas.",
  },
  {
    id: "tormenta",
    nombre: "Tormenta",
    icono: "⛈️",
    familia: "tecnito",
    categoria: "Fenómenos naturales",
    personaje: "sismo",
    motor: Quiz,
    banco: "tormenta",
    rondas: 5,
    segundos: 18,
    xp: 150,
    descripcion: "Rayos, viento y lluvia. Decide dónde te refugias y qué desconectas.",
  },
  {
    id: "simulador-emergencia",
    nombre: "Simulador de emergencia",
    icono: "🚨",
    familia: "tecnito",
    categoria: "Jefes finales",
    personaje: "sismo",
    motor: Simulacion,
    simulacion: "simulador-emergencia",
    xp: 260,
    descripcion: "El jefe final de Tecnito: alerta, protección, evacuación, mochila, punto de reunión y comunicación.",
    comoSeJuega: "Seis fases en orden. Cada decisión mueve la seguridad, la calma, el tiempo y la comunicación del grupo.",
  },
  {
    id: "comandante-emergencias",
    nombre: "Comandante de emergencias",
    icono: "🧑‍🚒",
    familia: "tecnito",
    categoria: "Jefes finales",
    personaje: "sismo",
    motor: Simulacion,
    simulacion: "comandante-emergencias",
    xp: 340,
    descripcion: "Diriges el centro de mando con unidades contadas. Rescate, salud, refugios e información al mismo tiempo.",
    comoSeJuega: "Cada despliegue cuesta unidades. Lo difícil no es una tarea: es no abandonar las otras tres.",
  },

  /* =========================== 🌱 GREENCITO =========================== */
  {
    id: "clasifica-basura",
    nombre: "Clasifica la basura",
    icono: "♻️",
    familia: "greencito",
    categoria: "Reciclaje",
    personaje: "green",
    motor: Clasifica,
    clasificacion: "clasifica-basura",
    rondas: 12,
    segundos: 8,
    xp: 0,
    descripcion: "Seis contenedores: orgánico, papel, plástico, vidrio, metal y no reciclable.",
    comoSeJuega: "Arrastra el residuo al contenedor o tócalo directamente.",
  },
  {
    id: "planta-arbol",
    nombre: "Planta un árbol",
    icono: "🌱",
    familia: "greencito",
    categoria: "Naturaleza",
    personaje: "green",
    motor: Cultiva,
    cultivo: "planta-arbol",
    xp: 0,
    descripcion: "Especie, temporada, hoyo, agua y cuidados. El árbol crece con tus decisiones.",
    comoSeJuega: "Sin cronómetro: aquí se trata de pensarle.",
  },
  {
    id: "repara-fuga",
    nombre: "Repara la fuga",
    icono: "💧",
    familia: "greencito",
    categoria: "Agua",
    personaje: "green",
    motor: Busca,
    escenas: "repara-fuga",
    objetivos: 5,
    segundos: 50,
    verbo: "fugas",
    xp: 0,
    descripcion: "Encuentra por dónde se está yendo el agua de la casa.",
    comoSeJuega: "Toca cada fuga para repararla. Ojo: no todo lo que gotea es fuga.",
  },
  {
    id: "carrera-reciclaje",
    nombre: "Carrera del reciclaje",
    icono: "🏃",
    familia: "greencito",
    categoria: "Reciclaje",
    personaje: "green",
    motor: BasuraCentro,
    xp: 0,
    dificultades: ["facil", "dificil"],
    descripcion: "Llegan diez residuos, uno por uno, contra reloj.",
    comoSeJuega: "Orgánico, reciclable o peligroso. Tres seguidos y los puntos se duplican.",
  },
  {
    id: "ahorra-agua",
    nombre: "Ahorra agua",
    icono: "🚿",
    familia: "greencito",
    categoria: "Agua",
    personaje: "green",
    motor: Quiz,
    banco: "ahorra-agua",
    rondas: 6,
    segundos: 18,
    xp: 40,
    descripcion: "Situaciones de consumo diario. Elige la opción más eficiente.",
  },
  {
    id: "apaga-luces",
    nombre: "Apaga las luces",
    icono: "💡",
    familia: "greencito",
    categoria: "Energía",
    personaje: "green",
    motor: Busca,
    escenas: "apaga-luces",
    objetivos: 5,
    segundos: 45,
    verbo: "aparatos",
    xp: 60,
    descripcion: "Encuentra todo lo que está gastando luz sin que nadie lo use.",
    comoSeJuega: "Cuidado: hay cosas que sí deben quedarse encendidas.",
  },
  {
    id: "limpia-rio",
    nombre: "Limpia el río",
    icono: "🌊",
    familia: "greencito",
    categoria: "Naturaleza",
    personaje: "green",
    motor: Busca,
    escenas: "limpia-rio",
    objetivos: 5,
    segundos: 50,
    verbo: "residuos",
    xp: 80,
    descripcion: "Saca la basura del río sin molestar a lo que sí vive ahí.",
  },
  {
    id: "transporte",
    nombre: "Transporte sostenible",
    icono: "🚲",
    familia: "greencito",
    categoria: "Cambio climático",
    personaje: "green",
    motor: Quiz,
    banco: "transporte",
    rondas: 5,
    segundos: 18,
    xp: 100,
    descripcion: "Elige cómo moverte con el menor impacto posible.",
  },
  {
    id: "reforestacion",
    nombre: "Reforestación",
    icono: "🌳",
    familia: "greencito",
    categoria: "Naturaleza",
    personaje: "green",
    motor: Cultiva,
    cultivo: "reforestacion",
    xp: 140,
    descripcion: "Un cerro pelón completo. Piensa en el sistema, no en un árbol.",
    comoSeJuega: "Cinco decisiones grandes: dónde, qué especies, suelo, ganado y seguimiento.",
  },

  {
    id: "casa-eficiente",
    nombre: "Casa eficiente",
    icono: "🏠",
    familia: "greencito",
    categoria: "Energía",
    personaje: "green",
    motor: Busca,
    escenas: "casa-eficiente",
    objetivos: 5,
    segundos: 55,
    verbo: "desperdicios",
    xp: 100,
    descripcion: "Encuentra lo que está desperdiciando agua, luz y dinero en tu casa.",
  },
  {
    id: "captura-lluvia",
    nombre: "Captura de lluvia",
    icono: "🌧️",
    familia: "greencito",
    categoria: "Agua",
    personaje: "green",
    motor: Construye,
    construccion: "captura-lluvia",
    xp: 120,
    descripcion: "Arma el sistema de captación del techo de tu escuela y aguanta la temporada de lluvias.",
    comoSeJuega: "Captación, canaletas, primeras lluvias, filtro y almacenamiento. En ese orden.",
  },
  {
    id: "polinizadores",
    nombre: "Polinizadores",
    icono: "🐝",
    familia: "greencito",
    categoria: "Naturaleza",
    personaje: "green",
    motor: Ruta,
    rutas: "polinizadores",
    recolectarTodo: true,
    iconos: { E: "🌸", S: "🏠", X: "🧪" },
    xp: 80,
    descripcion: "Lleva el polen entre todas las flores del jardín y regresa a la colmena.",
    comoSeJuega: "Muévete con flechas, WASD o la cruceta. La colmena no abre hasta que visites todas las flores.",
  },
  {
    id: "energia-solar",
    nombre: "Construye un sistema solar",
    icono: "☀️",
    familia: "greencito",
    categoria: "Energía",
    personaje: "green",
    motor: Coloca,
    colocacion: "energia-solar",
    segundos: 60,
    xp: 160,
    descripcion: "Coloca los paneles en el techo buscando la mayor producción posible.",
    comoSeJuega: "Sombra, orientación y obstáculos. En fácil se ve el rendimiento de cada casilla; en difícil hay que deducirlo.",
  },
  {
    id: "energia-eolica",
    nombre: "Energía eólica",
    icono: "🌬️",
    familia: "greencito",
    categoria: "Energía",
    personaje: "green",
    motor: Coloca,
    colocacion: "energia-eolica",
    segundos: 60,
    xp: 200,
    descripcion: "Levanta el parque eólico de la comunidad donde de verdad sopla el viento.",
    comoSeJuega: "Ojo con poner dos turbinas en la misma línea de viento: la de atrás recibe aire revuelto.",
  },
  {
    id: "salva-planeta",
    nombre: "Salva el planeta",
    icono: "🌎",
    familia: "greencito",
    categoria: "Cambio climático",
    personaje: "green",
    motor: Simulacion,
    simulacion: "salva-planeta",
    xp: 240,
    descripcion: "Seis años decidiendo por una región. Aire, bosques, agua, biodiversidad y bienestar a la vez.",
    comoSeJuega: "Casi ninguna decisión es gratis: sube unas cosas y baja otras.",
  },
  {
    id: "ecosistema",
    nombre: "Salva el ecosistema",
    icono: "🧬",
    familia: "greencito",
    categoria: "Naturaleza",
    personaje: "green",
    motor: Simulacion,
    simulacion: "ecosistema",
    xp: 220,
    descripcion: "Plantas, herbívoros, depredadores, insectos y agua. Mantén el equilibrio ocho temporadas.",
    comoSeJuega: "Entre turnos el ecosistema se mueve solo: los herbívoros comen plantas y los depredadores comen herbívoros.",
  },
  {
    id: "ciudad-sostenible",
    nombre: "Ciudad sostenible",
    icono: "🏙️",
    familia: "greencito",
    categoria: "Cambio climático",
    personaje: "green",
    motor: Simulacion,
    simulacion: "ciudad-sostenible",
    xp: 300,
    descripcion: "Administras una ciudad de 200 mil habitantes con presupuesto contado.",
    comoSeJuega: "Vivienda, servicios, agua, energía, verde y residuos. Todos tienen que llegar a su meta.",
  },

  /* ============================ 🧠 DESAFÍOS ============================ */
  {
    id: "quiz-relampago",
    nombre: "Quiz relámpago",
    icono: "⚡",
    familia: "general",
    categoria: "Velocidad",
    personaje: "sismo",
    motor: Quiz,
    banco: "quiz-relampago",
    rondas: 10,
    segundos: 12,
    xp: 0,
    descripcion: "Preguntas de todo, contra reloj. Mezcla Tecnito y Greencito.",
  },
  {
    id: "verdadero-falso",
    nombre: "Verdadero o falso",
    icono: "🔴",
    familia: "general",
    categoria: "Lógica",
    personaje: "green",
    motor: Quiz,
    banco: "verdadero-falso",
    rondas: 10,
    segundos: 14,
    xp: 0,
    descripcion: "Afirmaciones que suenan bien pero no siempre lo son.",
  },
  {
    id: "atrapa-respuesta",
    nombre: "Atrapa la respuesta",
    icono: "🎯",
    familia: "general",
    categoria: "Velocidad",
    personaje: "sismo",
    motor: Atrapa,
    bancos: ["quiz-relampago", "agachate", "ahorra-agua"],
    rondas: 8,
    segundos: 15,
    xp: 40,
    descripcion: "Las respuestas no se están quietas. Lee rápido y atrapa la buena.",
  },
  {
    id: "reto-contrarreloj",
    nombre: "Reto contrarreloj",
    icono: "⏱️",
    familia: "general",
    categoria: "Velocidad",
    personaje: "sismo",
    motor: Quiz,
    bancos: ["agachate", "incendio", "extintor", "ahorra-agua", "transporte", "quiz-relampago"],
    rondas: 12,
    segundos: 10,
    xp: 120,
    descripcion: "Doce preguntas de todo el escuadrón con muy poco tiempo cada una.",
  },
  {
    id: "ruleta-educativa",
    nombre: "Ruleta educativa",
    icono: "🎲",
    familia: "general",
    categoria: "Retos especiales",
    personaje: "green",
    motor: Ruleta,
    ruleta: "ruleta-educativa",
    rondas: 6,
    segundos: 18,
    xp: 60,
    descripcion: "Gira, cae en una categoría y contesta lo que salga.",
  },
  {
    id: "palabras-ocultas",
    nombre: "Palabras ocultas",
    icono: "🔤",
    familia: "general",
    categoria: "Puzzle",
    personaje: "green",
    motor: Sopa,
    sopa: "palabras-ocultas",
    palabras: 5,
    segundos: 120,
    xp: 60,
    descripcion: "Sopa de letras de protección civil y medio ambiente, distinta cada partida.",
    comoSeJuega: "Toca la primera letra y luego la última. En difícil también hay diagonales y palabras al revés.",
  },
  {
    id: "rompecabezas",
    nombre: "Rompecabezas",
    icono: "🧩",
    familia: "general",
    categoria: "Puzzle",
    personaje: "sismo",
    motor: Puzzle,
    rompecabezas: "rompecabezas",
    segundos: 150,
    xp: 80,
    descripcion: "Arma a Tecnito o a Greencito deslizando las piezas.",
    comoSeJuega: "Fácil es de 3×3; medio y difícil, de 4×4.",
  },
  {
    id: "codigo-secreto",
    nombre: "Código secreto",
    icono: "🔐",
    familia: "general",
    categoria: "Lógica",
    personaje: "sismo",
    motor: Codigo,
    codigo: "codigo-secreto",
    segundos: 150,
    xp: 100,
    descripcion: "Descifra la combinación por deducción. Cada caja abierta suelta un dato útil.",
    comoSeJuega: "Te dicen cuántos símbolos están en su lugar y cuántos están en la clave pero mal puestos.",
  },
  {
    id: "tecnito-vs-greencito",
    nombre: "Tecnito vs Greencito",
    icono: "🏆",
    familia: "general",
    categoria: "Retos especiales",
    personaje: "sismo",
    motor: Simulacion,
    simulacion: "tecnito-vs-greencito",
    xp: 420,
    descripcion: "El gran desafío: una ciudad 100% segura y 100% sostenible, con un solo presupuesto.",
    comoSeJuega: "Siete indicadores, cuatro de Greencito y tres de Tecnito. Hay que llevarlos todos a la meta.",
  },

  {
    id: "memorama",
    nombre: "Memorama educativo",
    icono: "🧠",
    familia: "general",
    categoria: "Memoria",
    personaje: "sismo",
    motor: MemoramaCentro,
    xp: 0,
    dificultades: ["facil", "dificil"],
    descripcion: "Seis parejas contra reloj. Cada acierto suelta un dato.",
    comoSeJuega: "En difícil no emparejas cartas iguales: emparejas la situación con su respuesta.",
  },
];

export const POR_ID = Object.fromEntries(JUEGOS.map((j) => [j.id, j]));

/** Categorías en el orden en que se muestran en el Centro. */
export function categoriasDe(familia) {
  const vistas = [];
  JUEGOS.filter((j) => j.familia === familia).forEach((j) => {
    if (!vistas.includes(j.categoria)) vistas.push(j.categoria);
  });
  return vistas;
}

/**
 * Un juego se desbloquea con XP acumulada. Es a propósito generoso:
 * la mitad del catálogo está disponible desde el primer minuto.
 */
export function estaDesbloqueado(juego, progreso) {
  return (progreso?.xp || 0) >= (juego.xp || 0);
}

export function siguienteEnDesbloquear(progreso) {
  const xp = progreso?.xp || 0;
  return JUEGOS.filter((j) => j.xp > xp).sort((a, b) => a.xp - b.xp)[0] || null;
}
